# Site settings
title: Illinois Voices for Reform
email: info@ilvoices.com
description: >
  Illinois Voices fights for and supports laws that MAKE SENSE, ones that actually make society safer while protecting the constitutional rights of everyone involved. We believe laws should be passed based on research and empirical evidence of what works and what does not. “Feel good” laws based on public hysteria surrounding high-profile, but rare cases waste taxpayer dollars, violate the rights of individuals, and can actually detract from public safety.
baseurl: ""
url: "http://ilvoices.github.io"

# Build settings
markdown: kramdown
